from core.WorkflowFactory import WorkflowFactory

from industries.healthcare.workflows.customer.main_menu_workflow import MainMenuWorkflow
from industries.healthcare.workflows.customer.select_patient_workflow import SelectPatientWorkflow
from industries.healthcare.workflows.customer.select_doctor_workflow import SelectDoctorWorkflow
from industries.healthcare.workflows.customer.select_consultation_workflow import SelectConsultationWorkflow
from industries.healthcare.workflows.customer.select_date_workflow import SelectDateWorkflow
from industries.healthcare.workflows.customer.select_time_slot_workflow import SelectTimeSlotWorkflow
from industries.healthcare.workflows.customer.process_payment_workflow import ProcessPaymentWorkflow
from industries.healthcare.workflows.customer.confirm_booking_workflow import ConfirmBookingWorkflow
from industries.healthcare.workflows.customer.view_appointments_workflow import ViewAppointmentsWorkflow
from industries.healthcare.workflows.customer.select_appointment_to_cancel_workflow import SelectAppointmentToCancelWorkflow
from industries.healthcare.workflows.customer.confirm_cancellation_workflow import ConfirmCancellationWorkflow
from industries.healthcare.workflows.customer.register_patient_workflow import RegisterPatientWorkflow
from industries.healthcare.workflows.customer.collect_email_workflow import CollectEmailWorkflow
from industries.healthcare.workflows.doctor.doctor_menu_workflow import DoctorMenuWorkflow
from industries.healthcare.workflows.doctor.doctor_view_schedule_workflow import DoctorViewScheduleWorkflow
from industries.healthcare.workflows.doctor.doctor_patient_details_workflow import DoctorPatientDetailsWorkflow
from industries.healthcare.workflows.doctor.doctor_cancel_appointment_workflow import (
    DoctorSelectAppointmentsToCancelWorkflow,
    DoctorCancelAppointmentsWorkflow,
    DoctorCancellationConfirmationWorkflow,
)
from industries.healthcare.workflows.doctor.doctor_refund_workflow import (
    DoctorViewRefundsWorkflow,
    DoctorProcessRefundWorkflow,
)
from industries.healthcare.workflows.admin.admin_menu_workflow import AdminMenuWorkflow


industry = "DoctorAppointment."

# Self-register at import time
WorkflowFactory.register(industry+"MainMenuWorkflow", MainMenuWorkflow)
WorkflowFactory.register(industry+"SelectPatientWorkflow", SelectPatientWorkflow)
WorkflowFactory.register(industry+"SelectDoctorWorkflow", SelectDoctorWorkflow)
WorkflowFactory.register(industry+"SelectConsultationWorkflow", SelectConsultationWorkflow)
WorkflowFactory.register(industry+"SelectDateWorkflow", SelectDateWorkflow)
WorkflowFactory.register(industry+"SelectTimeSlotWorkflow", SelectTimeSlotWorkflow)
WorkflowFactory.register(industry+"ProcessPaymentWorkflow", ProcessPaymentWorkflow)
WorkflowFactory.register(industry+"ConfirmBookingWorkflow", ConfirmBookingWorkflow)
WorkflowFactory.register(industry+"ViewAppointmentsWorkflow", ViewAppointmentsWorkflow)
WorkflowFactory.register(industry+"SelectAppointmentToCancelWorkflow", SelectAppointmentToCancelWorkflow)
WorkflowFactory.register(industry+"ConfirmCancellationWorkflow", ConfirmCancellationWorkflow)
WorkflowFactory.register(industry+"RegisterPatientWorkflow", RegisterPatientWorkflow)
WorkflowFactory.register(industry+"CollectEmailWorkflow", CollectEmailWorkflow)
WorkflowFactory.register(industry+"DoctorMenuWorkflow", DoctorMenuWorkflow)
WorkflowFactory.register(industry+"DoctorViewScheduleWorkflow", DoctorViewScheduleWorkflow)
WorkflowFactory.register(industry+"DoctorPatientDetailsWorkflow", DoctorPatientDetailsWorkflow)
WorkflowFactory.register(industry+"DoctorSelectAppointmentsToCancelWorkflow", DoctorSelectAppointmentsToCancelWorkflow)
WorkflowFactory.register(industry+"DoctorCancelAppointmentsWorkflow", DoctorCancelAppointmentsWorkflow)
WorkflowFactory.register(industry+"DoctorCancellationConfirmationWorkflow", DoctorCancellationConfirmationWorkflow)
WorkflowFactory.register(industry+"DoctorViewRefundsWorkflow", DoctorViewRefundsWorkflow)
WorkflowFactory.register(industry+"DoctorProcessRefundWorkflow", DoctorProcessRefundWorkflow)
WorkflowFactory.register(industry+"AdminMenuWorkflow", AdminMenuWorkflow)

from industries.healthcare.workflows.common.GreetingMessageWorkflow import GreetingMessageWorkflow
from industries.healthcare.workflows.common.ExitWorkflow import ExitWorkflow

WorkflowFactory.register(industry+"GreetingMessageWorkflow", GreetingMessageWorkflow)
WorkflowFactory.register(industry+"ExitWorkflow", ExitWorkflow)
