from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class ReportSummary(BaseModel):
    Revenue: float = Field(0.0, description="Total revenue generated in period")
    RevenueGrowth: str = Field("0.0%", description="Revenue growth percentage compared to previous period")
    Orders: int = Field(0, description="Total order count in period")
    OrdersGrowth: str = Field("0.0%", description="Orders growth percentage compared to previous period")
    Customers: int = Field(0, description="Total unique customer count in period")
    CustomersGrowth: str = Field("0.0%", description="Customer count growth percentage compared to previous period")
    ProductsSold: int = Field(0, description="Total units of products sold in period")
    ProductsSoldGrowth: str = Field("0.0%", description="Products sold growth percentage compared to previous period")

    class Config:
        from_attributes = True

class TopProductItem(BaseModel):
    ProductName: str = Field(..., description="Product title / name")
    Category: Optional[str] = Field("General", description="Category classification")
    UnitSold: int = Field(0, description="Units / Quantity sold in period")
    Revenue: float = Field(0.0, description="Total revenue generated by product in period")
    Revenuegrowth: str = Field("0.0%", description="Product revenue growth percentage compared to previous period")

    class Config:
        from_attributes = True

class RecentSaleItem(BaseModel):
    OrdeId: str = Field(..., description="Order ID or Number")
    CustomerName: Optional[str] = Field("Customer", description="Customer Name")
    product: Optional[str] = Field("", description="Product name(s)")
    Amount: float = Field(0.0, description="Total order amount")
    Status: str = Field("Pending", description="Order fulfillment status")
    Date: str = Field(..., description="Order date formatted")

    class Config:
        from_attributes = True

class EcommerceReportOut(BaseModel):
    Period: str = Field("AllTime", description="Selected calculation period: Day, Week, Month, AllTime, or custom filter")
    summary: ReportSummary = Field(default_factory=ReportSummary, description="High-level performance summary for selected period")
    revenueOverview: Dict[str, Any] = Field(default_factory=dict, description="Revenue and orders overview breakdown by date")
    TopProducts: List[TopProductItem] = Field(default_factory=list, description="Top selling products ranked by revenue in selected period")
    RecentSales: List[RecentSaleItem] = Field(default_factory=list, description="List of recent order transactions in selected period")

    class Config:
        from_attributes = True
