"""initial_tables

Revision ID: d847afd05c81
Revises: 
Create Date: 2026-09-01 15:35:16.738598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd847afd05c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_requests',
    sa.Column('DemoId', sa.String(length=36), nullable=False),
    sa.Column('BusinessName', sa.String(length=150), nullable=False),
    sa.Column('BusinessType', sa.String(length=100), nullable=True),
    sa.Column('Locations', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=100), nullable=True),
    sa.Column('State', sa.String(length=100), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('FullName', sa.String(length=150), nullable=False),
    sa.Column('Designation', sa.String(length=100), nullable=True),
    sa.Column('WorkEmail', sa.String(length=150), nullable=False),
    sa.Column('MobileNumber', sa.String(length=20), nullable=False),
    sa.Column('WhatsappNumber', sa.String(length=20), nullable=True),
    sa.Column('PreferredDate', sa.String(length=50), nullable=True),
    sa.Column('PreferredTime', sa.String(length=50), nullable=True),
    sa.Column('PreferredDemoMode', sa.String(length=100), nullable=True),
    sa.Column('DemoRequirements', sa.Text(), nullable=True),
    sa.Column('AgreeToContact', sa.Boolean(), nullable=False),
    sa.Column('SelectedIndustry', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('DemoId')
    )
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_requests_DemoId'), ['DemoId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_requests_DemoId'))

    op.drop_table('demo_requests')
    # ### end Alembic commands ###
