from core.workflow.WorkflowFactory import WorkflowFactory

from industries.ecommerce.workflows.customer.main_menu_workflow import MainMenuWorkflow as EcommerceMainMenuWorkflow
from industries.ecommerce.workflows.customer.select_category_workflow import SelectCategoryWorkflow
from industries.ecommerce.workflows.customer.select_product_workflow import SelectProductWorkflow
from industries.ecommerce.workflows.customer.select_variant_workflow import SelectVariantWorkflow
from industries.ecommerce.workflows.customer.select_quantity_workflow import SelectQuantityWorkflow
from industries.ecommerce.workflows.customer.collect_name_workflow import CollectNameWorkflow
from industries.ecommerce.workflows.customer.collect_phone_workflow import CollectPhoneWorkflow
from industries.ecommerce.workflows.customer.collect_address_workflow import CollectAddressWorkflow
from industries.ecommerce.workflows.customer.select_delivery_slot_workflow import SelectDeliverySlotWorkflow
from industries.ecommerce.workflows.customer.select_date_workflow import SelectDateWorkflow as EcommerceSelectDateWorkflow
from industries.ecommerce.workflows.customer.select_payment_workflow import SelectPaymentWorkflow
from industries.ecommerce.workflows.customer.confirm_order_workflow import ConfirmOrderWorkflow
from industries.ecommerce.workflows.customer.track_order_workflow import TrackOrderWorkflow
from industries.ecommerce.workflows.customer.handoff_to_whatsapp_workflow import HandoffToWhatsAppWorkflow
from industries.ecommerce.workflows.owner.owner_menu_workflow import OwnerMenuWorkflow
from industries.ecommerce.workflows.owner.view_pending_orders_workflow import ViewPendingOrdersWorkflow
from industries.ecommerce.workflows.owner.update_order_status_workflow import UpdateOrderStatusWorkflow

# Self-register at import time
WorkflowFactory.register("OrderingMainMenuWorkflow", EcommerceMainMenuWorkflow)
WorkflowFactory.register("SelectCategoryWorkflow", SelectCategoryWorkflow)
WorkflowFactory.register("SelectProductWorkflow", SelectProductWorkflow)
WorkflowFactory.register("SelectVariantWorkflow", SelectVariantWorkflow)
WorkflowFactory.register("SelectQuantityWorkflow", SelectQuantityWorkflow)
WorkflowFactory.register("CollectNameWorkflow", CollectNameWorkflow)
WorkflowFactory.register("CollectPhoneWorkflow", CollectPhoneWorkflow)
WorkflowFactory.register("CollectAddressWorkflow", CollectAddressWorkflow)
WorkflowFactory.register("SelectDeliverySlotWorkflow", SelectDeliverySlotWorkflow)
WorkflowFactory.register("EcommerceSelectDateWorkflow", EcommerceSelectDateWorkflow)
WorkflowFactory.register("SelectPaymentWorkflow", SelectPaymentWorkflow)
WorkflowFactory.register("ConfirmOrderWorkflow", ConfirmOrderWorkflow)
WorkflowFactory.register("TrackOrderWorkflow", TrackOrderWorkflow)
WorkflowFactory.register("HandoffToWhatsAppWorkflow", HandoffToWhatsAppWorkflow)
WorkflowFactory.register("OwnerMenuWorkflow", OwnerMenuWorkflow)
WorkflowFactory.register("ViewPendingOrdersWorkflow", ViewPendingOrdersWorkflow)
WorkflowFactory.register("UpdateOrderStatusWorkflow", UpdateOrderStatusWorkflow)
